'use strict';

const tips = [
  '💡 *Regra 50/30/20:* Destine 50% para necessidades, 30% para desejos e 20% para investimentos.',
  '💡 *Fundo de emergência:* Guarde pelo menos 6 meses dos seus gastos mensais em um investimento seguro e de liquidez diária.',
  '💡 *Compra por impulso:* Espere 48 horas antes de comprar qualquer coisa não planejada. Se ainda quiser depois disso, compre.',
  '💡 *Automatize investimentos:* Programe uma transferência automática para seus investimentos logo no dia em que receber seu salário.',
  '💡 *Anote seus gastos:* Registrar suas despesas por 30 dias revela para onde seu dinheiro realmente está indo.',
  '💡 *Cartão de crédito:* Use-o como ferramenta de pagamento, não como extensão do salário. Pague sempre o valor total da fatura.',
  '💡 *Inflação invisível:* Pequenos gastos diários (como café ou delivery frequente) acumulados podem custar mais de R$500/mês.',
  '💡 *Renegocie dívidas:* Elimine dívidas com juros altos (cartão de crédito, cheque especial) antes de começar a investir em renda variável.',
  '💡 *Metas financeiras:* Defina metas específicas com prazo e valor. "Quero economizar" sem um número ou prazo não funciona.',
  '💡 *Invista em você:* Cursos, livros e novas habilidades têm o melhor retorno financeiro a longo prazo.',
  '💡 *Pague-se primeiro:* Poupe e invista uma parte do seu salário assim que ele cair na conta, antes de começar a pagar as contas do mês.',
  '💡 *Custo por uso:* Antes de comprar algo caro, calcule o custo por uso (Preço dividido pelo número de vezes que você estima usar).',
  '💡 *Assinaturas inativas:* Revise seus extratos e cancele serviços de streaming ou assinaturas que você não utiliza há mais de um mês.',
  '💡 *Supermercado consciente:* Nunca vá ao supermercado com fome e sempre leve uma lista de compras detalhada.',
  '💡 *Pesquise preços:* Use ferramentas de comparação de preços online e busque cupons de desconto antes de qualquer compra significativa.',
  '💡 *Diversificação:* Nunca coloque todos os seus ovos na mesma cesta. Diversifique seus investimentos entre renda fixa e renda variável.',
  '💡 *Juros compostos:* Os juros compostos são seus melhores amigos no longo prazo. Quanto mais cedo você começar a investir, menor será o esforço necessário.',
  '💡 *Padrão de vida:* Evite aumentar seu padrão de vida na mesma proporção que seu salário aumenta. Guarde e invista a diferença.',
  '💡 *Renda extra:* Dedique algumas horas da sua semana para desenvolver uma fonte de renda extra usando habilidades que você já possui.',
  '💡 *Taxas bancárias:* Verifique se você está pagando tarifas de conta corrente ou anuidade de cartão de crédito. Migre para opções gratuitas ou negocie-as.',
  '💡 *Manutenção preventiva:* Fazer manutenção periódica no seu carro ou na sua casa evita despesas muito maiores com reparos de emergência.',
  '💡 *Cashback e Milhas:* Aproveite programas de cashback e milhas em compras que você já faria de qualquer forma, mas evite gastar mais apenas para acumular pontos.',
  '💡 *Perfil de investidor:* Conheça o seu perfil (conservador, moderado ou arrojado) antes de investir para não correr riscos desalinhados com suas expectativas.',
  '💡 *Cuidado com pirâmides:* Desconfie de promessas de ganhos rápidos, fáceis ou retornos garantidos muito acima da média do mercado.',
  '💡 *Seguros:* Ter seguros adequados (de vida, saúde ou bens de alto valor) protege seu patrimônio de imprevistos catastróficos.',
  '💡 *Regra de 1%:* Se o valor de uma compra supérflua for superior a 1% da sua renda anual, espere uma semana antes de fechar o negócio.',
  '💡 *Investir não é apostar:* O mercado financeiro premia a paciência e a consistência. Evite especulações arriscadas com dinheiro que você não pode perder.',
  '💡 *Negocie sempre:* Não hesite em pedir desconto para pagamentos à vista ou renegociar contratos de internet, telefone e seguros anualmente.',
  '💡 *Mentalidade de riqueza:* Foque em aumentar sua renda e adquirir ativos (coisas que colocam dinheiro no seu bolso), em vez de apenas acumular passivos.',
  '💡 *Orçamento base zero:* Aloque cada centavo do seu rendimento mensal a uma categoria específica antes do mês começar, para que nenhum dinheiro fique "sobrando" sem destino.',
  '💡 *Inflação pessoal:* A inflação oficial pode ser diferente da sua. Acompanhe seus gastos para entender como a alta dos preços afeta seu orçamento específico.',
  '💡 *Pesquisa de satisfação:* Ao comprar um produto caro, leia avaliações negativas de outros usuários para entender os possíveis pontos fracos do item.',
  '💡 *Planejamento de aposentadoria:* Não dependa apenas da previdência pública. Comece a construir sua carteira de aposentadoria o quanto antes.',
  '💡 *Educação dos filhos:* Converse abertamente sobre dinheiro com seus filhos desde cedo para desenvolver neles uma relação saudável com as finanças.',
  '💡 *Aluguel vs Compra:* Avalie financeiramente se vale mais a pena morar de aluguel e investir a diferença ou financiar um imóvel próprio.',
  '💡 *Investimento em Renda Fixa:* Entenda a diferença entre CDB, LCI, LCA e Tesouro Direto. Eles são excelentes alternativas à poupança.',
  '💡 *Imposto de Renda:* Mantenha seus comprovantes de despesas médicas e de educação organizados ao longo do ano para facilitar sua declaração de IR.',
  '💡 *Balanço patrimonial:* Uma vez por ano, calcule seu patrimônio líquido (tudo o que você tem de valor menos tudo o que você deve).',
  '💡 *Reserva de oportunidade:* Além do fundo de emergência, tenha uma reserva para aproveitar boas oportunidades de investimento que surgem em momentos de queda do mercado.',
  '💡 *Consumo sustentável:* Pergunte-se sempre: "Eu realmente preciso disso? Eu preciso disso agora? Eu posso pagar por isso sem me endividar?"',
  '💡 *Foco no longo prazo:* Evite olhar seus investimentos de longo prazo diariamente. A oscilação diária é normal e não deve abalar sua estratégia.',
  '💡 *Dinheiro e relacionamento:* Alinhe as metas e planos financeiros com seu parceiro(a). A falta de diálogo sobre finanças é uma das maiores causas de atrito em casais.'
];

module.exports = tips;
